test: ensure that forking takes are received by all takers
redux-saga/redux-saga pull request #2206
Opened 2021-07-22 20:39 UTC by forivall

| Q                        | A  |
| ------------------------ | ---  |
| Fixed Issues?            | N/A |
| Patch: Bug Fix?          | No |
| Major: Breaking Change?  | No |
| Minor: New Feature?      | No |
| Tests Added + Pass?      | Yes |
| Any Dependency Changes?  | No |

I wanted to ensure that `take`s from multiple forked sagas are received by all of them for a single `put`. I didn't see anything in the documentation verifying this, and didn't see any tests verifying this scenario, so i added some tests to make sure that it's covered, and it is! Let me know if there are other tests for this. (my use case is indirectly composing sagas, ie, dispatching an action, and then waiting for the result action to dispatch/put)

I can also add a note in the documentation, probably in https://redux-saga.js.org/docs/advanced/FutureActions

2021-07-23 08:32 UTC, Andarist commented
Thank you for your contribution - to merge this in I would have to dive into our test suite to verify if those tests are not duplicates of some existing ones. I might not be able to do that any time soon though because my plate is quite full right now. I hope you understand.

2021-07-29 00:32 UTC, forivall commented
yeah, i understand. no worries.

2022-06-19 16:56 UTC, neurosnap requested changes
Thanks for your contribution and sorry for the delay.  I have reviewed all tests and don't see any tests that are similar to the ones written here.  It's possible that we are inadvertently testing these scenarios but I don't see anything wrong with including explicit tests written in this PR.

I made a couple of suggested changes (even though we are making the same mistake in previous tests).

2022-06-19 16:56 UTC, neurosnap commented on packages/core/__tests__/interpreter/takeSync.js
> +  const store = createStore(reducer, applyMiddleware(middleware))
```suggestion
createStore(reducer, applyMiddleware(middleware))
```

2022-06-19 16:56 UTC, neurosnap commented on packages/core/__tests__/interpreter/takeSync.js
> +  const store = createStore(reducer, applyMiddleware(middleware))
```suggestion
createStore(reducer, applyMiddleware(middleware))
```

2022-07-26 13:44 UTC, neurosnap commented
I'm going to close this PR for now because it's been a year since it was actively worked on.  If someone wants to pick this up I'd be more than happy to review.  Thanks!

2022-07-26 13:44 UTC, closed without merging