#2385: fixed put/putResolve typings for thunk actions
redux-saga/redux-saga pull request #2386
Opened 2023-08-16 20:27 UTC by qkudev

| Q                       | A                                         |
| ----------------------- | ---------------------------------------------------------------------- |
| Fixed Issues?           | #2385 |
| Patch: Bug Fix?         | Yes                                                                        |
| Major: Breaking Change? | No                                     |
| Minor: New Feature?     | No                                   |
| Tests Added + Pass?     | No                                                                    |
| Any Dependency Changes? | No                                                                        |

2023-08-17 16:47 UTC, neurosnap commented
Greetings!

Thanks so much for your contribution!  Could you please add a couple of tests to https://github.com/redux-saga/redux-saga/blob/main/packages/core/types/effects.test.ts#L94

That will fail without your changes?

Thanks!

2023-08-19 06:47 UTC, qkudev commented
Thanks for feedback

Done!

Waiting for your review

2023-08-24 03:04 UTC, anandfresh approved these changes

2023-08-24 13:07 UTC, neurosnap requested changes
Thanks so much!  We are almost there, just need more tests here:

https://github.com/redux-saga/redux-saga/blob/9c2af0c453898bd4c9eef42b364f9f6f212adb2e/packages/core/types/ts3.6/effects.test.ts#L94

2023-08-25 15:30 UTC, neurosnap requested changes
One last request: please add a changeset by running `yarn changeset` in the root and make it a `patch`:

```
---
'@redux-saga/core': patch
---

Fixes `put`/`putResolve` typings to support thunk actions
```

2023-08-26 14:40 UTC, neurosnap approved these changes

2023-08-26 15:34 UTC, merged